export const up = async client => {
  await client `
    CREATE TABLE IF NOT EXISTS public.enums (
      id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      enum_name VARCHAR(200) NOT NULL,
      enum_value INT NOT NULL,
      table_context VARCHAR(200),
      context VARCHAR(2000),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;

  await client`
    CREATE TRIGGER set_timestamp
    BEFORE UPDATE ON public.enums
    FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();
  `;
};

export const down = async client => {
  await client`
    DROP TRIGGER IF EXISTS set_timestamp ON public.enums;
  `;

  await client `
    DROP TABLE IF EXISTS public.enums;
  `
};
