export const up = async client => {
  await client `
    CREATE TABLE IF NOT EXISTS public.enums (
      id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      enum_name VARCHAR(200) NOT NULL,
      enum_value INT NOT NULL,
      table_context VARCHAR(200),
      context VARCHAR(2000),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
};

export const down = async client => {
  await client `
    DROP TABLE IF EXISTS public.enums
  `
};
